apiVersion: v1
kind: Service
metadata:
  name: "svc-{{ .Release.Name }}"
  namespace: default
spec:
  type: "{{ .Values.service.type }}"
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: "{{ .Chart.Name }}"
