apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  volumes:
  - name: html
    hostPath:
      path: /webdata
  containers:
  - image: nginx:1.14
    name: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
